---
layout: cv
title: Allan Panameno's CV
---
# Allan Panameno
385-358-4060 | pan20004@byui.edu | www.linkedin.com/in/allanpanameno




## Education

Major: B.S Business Analytics - 
GPA: 3.85 

Minor: Supply Chain Management
Brigham Young University – Idaho
Certificates:
- Marketing Principles
- Customer Service
Relevant Courses:
Financial & Managerial Accounting, Investment, Database Design, Business Analytics, and Operations
Management

## Experience

Online Academic Support Hiring Assistant June 2022 – Present
Brigham Young University – Idaho Rexburg, Idaho
 Demonstrated proficiency in Excel and Power BI by using advanced functions to analyze and present
data to support decision-making processes.
 Organized and maintained job postings for teaching assistant positions across three university platforms.
 Built strong relationships with department chairs, professors, and teaching assistants in the business,
accounting, computer science, and healthcare departments.
 Mentored a diverse group of over 50 students by actively improving their performance and academic
experience.
 Ensured compliance with federal regulations by verifying I-9 forms and other documents.

Full-time Volunteer Representative January 2020 – January 2022
The Church of Jesus Christ of Latter-day Saints Nicaragua, Belize, and El Salvador
 Analyzed data from multiple volunteer groups to identify trends, issues, and improvements.
 Utilized strong negotiation skills to secure favorable pricing agreements with suppliers across Nicaragua.
 Scheduled delivery routes, exceeded delivery goals by 85%, and managed ecclesiastical materials
ensuring delivery and quality control.
 Developed leadership skills through several responsibility positions moving hard work among large
groups.

## SKILLS AND TECHNICAL COMPETENCIES
 Proficient with Excel, PowerPoint, Microsoft Word, Python, MySQL, R Studio, and Canva Design.
 Native Spanish speaker; Fluent in English.



<!-- ### Footer

Last updated: May 2013 -->